export const GET_INIT_DATA = ' GET_INIT_DATA';

export const START_FETCH_PLAYERS = ' START_FETCH_PLAYERS';
export const END_FETCH_PLAYERS = ' END_FETCH_PLAYERS';
export const CLEAR_PLAYERS = ' CLEAR_PLAYERS';
export const START_SET_TRAINING = ' START_SET_TRAINING';
export const END_SET_TRAINING = ' END_SET_TRAINING';
